_target_: flax.nnx.Optimizer
tx:
  _target_: optax.chain
  _args_:
    - _target_: optax.clip_by_global_norm
      max_norm: 0.5
    - _target_: optax.adam
      learning_rate: ${training.learning_rate}