_target_: flax.nnx.Optimizer
tx:
  _target_: optax.chain
  _args_:
    - _target_: optax.adam
      learning_rate: ${training.learning_rate}
    - _target_: optax.contrib.reduce_on_plateau
      factor: 0.5
      patience: 10
      accumulation_size: ${product:[${N}, 0.1]}