_target_: flax.nnx.Optimizer
tx:
  _target_: optax.adam
  learning_rate:
    _target_: optax.schedules.cosine_decay_schedule
    init_value: ${training.learning_rate}
    decay_steps: ${compute_train_steps:${training.epochs}, ${data_source.train.N}, ${training.batch_size}, ${data_source.train.n_realizations}}
    alpha: 0.0
