
num_variables: ${len:${data_source.base_dataset.var_keys}}
num_hypervariables: ${len:${data_source.base_dataset.hypervar_keys}}
num_output_variables: ${len:${data_source.base_dataset.target_keys}}

# HYPERNETWORK
hyper_block:
  _target_: models.Hypernetwork

  network:
    _target_: models.MLP
    num_neurons:
      - ${model.num_hypervariables}
      - 64
      - 64
      - 128
    activation_functions:
      _target_: models.get_tanh
    rngs:
      _target_: flax.nnx.Rngs
      default: ${seed}

  input: hypervars
  output: latent_features

# PROJECTION HEAD
proj_block:
  _target_: models.ProjectionHead
  in_features: 128
  input: latent_features
  output: weights
  kernel_init:
    _target_: flax.nnx.initializers.lecun_normal
  bias_init:
    _target_: flax.nnx.initializers.zeros_init
  rngs:
    _target_: flax.nnx.Rngs
    default: ${seed}

# TARGET NETWORK
target_block:
  _target_: models.TargetNetwork

  network:
    _target_: models.MLP
    num_neurons:
      - ${model.num_variables}
      - 8
      - 8
      - ${model.num_output_variables}
    activation_functions:
      _target_: models.get_tanh
    rngs:
      _target_: flax.nnx.Rngs
      default: ${seed}

  input: vars
  weights_mapping:
    all: weights
  output: final_output

# HYPERNETWORK MANAGER
manager:
  _target_: models.HypernetworkManager
  blocks:
    - ${model.target_block}
    - ${model.proj_block}
    - ${model.hyper_block}
  output: final_output