base_toy:
  _target_: data_processing.ToyDataSource
  
train:
  _target_: data_processing.ToyDataSource
  f: ${data_source.base_toy.f}
  hyper_domains: ${data_source.base_toy.hyper_domains}
  var_domains: ${data_source.base_toy.var_domains}
  N: 10000
  n_realizations: 1
  seed: ${seed}

val:
  _target_: data_processing.ToyDataSource
  f: ${data_source.base_toy.f}
  hyper_domains: ${data_source.base_toy.hyper_domains}
  var_domains: ${data_source.base_toy.var_domains}
  N: ${int_product:${data_source.train.N},0.2}
  n_realizations: ${data_source.train.n_realizations}
  seed: ${sum:[${seed},1]}

test:
  _target_: data_processing.ToyDataSource
  f: ${data_source.base_toy.f}
  hyper_domains: ${data_source.base_toy.hyper_domains}
  var_domains: ${data_source.base_toy.var_domains}
  N: ${int_product:${data_source.train.N},0.2}
  n_realizations: ${data_source.train.n_realizations}
  seed: ${sum:[${seed},2]}
