# "variable names to column indices" schema for this specific dataset type
schema: &schema
  time: 0
  x: 1
  y: 2
  density: 3
  pressure: 4
  velocity_x: 5
  velocity_y: 6

base_dataset: &base_dataset
  _target_: data_processing.InMemoryHDF5Source
  schema: *schema
  # use variable names as in schema to specify which variables to use as hyperparameters, input variables, and target variables
  hypervar_keys: ["time"]
  var_keys: ["x", "y"]
  target_keys: ["velocity_x", "velocity_y"]
  var_bounds: [[-0.5, 0.5], [-0.5, 0.5]]

train:
  <<: *base_dataset
  hdf5_path: ${dataset_root}/${preprocessing.data.base_name}_train.hdf5

val:
  <<: *base_dataset
  hdf5_path: ${dataset_root}/${preprocessing.data.base_name}_val.hdf5

test:
  <<: *base_dataset
  hdf5_path: ${dataset_root}/${preprocessing.data.base_name}_test.hdf5