epochs: 10000
batch_size: 1024

criterion:
  _target_: losses.L2Loss

metrics:
  RRMSE:
    _target_: metrics.RRMSE
  MAE:
    _target_: metrics.MAE
  RMSE:
    _target_: metrics.RMSE
  

early_stopping:
  _target_: training.EarlyStopping
  patience: 1000
  min_delta: 1.0e-8

early_stopping_metric: RRMSE