epochs: 200
batch_size: 4096
learning_rate: 1.0e-4
in_memory: true

metrics:
  RRMSE:
    _target_: metrics.RRMSE
  MAE:
    _target_: metrics.MAE
  RMSE:
    _target_: metrics.RMSE
  

early_stopping:
  _target_: flax.training.early_stopping.EarlyStopping
  patience: 200

early_stopping_metric: loss

checkpointing_frequency: 200