epochs: 50
batch_size: 4096
learning_rate: 1.0e-3
in_memory: true

criterion:
  _target_: losses.L2Loss

metrics:
  RRMSE:
    _target_: metrics.RRMSE
  MAE:
    _target_: metrics.MAE
  RMSE:
    _target_: metrics.RMSE
  

early_stopping:
  _target_: flax.training.early_stopping.EarlyStopping
  patience: 200

early_stopping_metric: RRMSE

checkpointing_frequency: 10

resume_from_checkpoint: null