hydra:
  job:
    name: default
    chdir: true
  run:
    dir: results/runs_${problem_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: results/multiruns_${problem_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

dataset_root: ${hydra:runtime.cwd}/datasets

defaults:
  - optimizer: adamw_cosine_decay_clipping
  - problem: turbulence            # Controller for consistency across configs: it can be toy or turbulence and realtes to data_source and postprocessing.
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

seed: 0

use_wandb: true
wandb_settings:
  project: JaxHypernetworks
  entity: pacs_rota_bocchieri

# NOTE: N for toy problem can be found at congif-time, while for turbulence problem it is determined at runtime.
# This is because for the turbulence problem, the number of variables (N) depends on the specific dataset and how it is processed, which may not be known until the data is loaded and analyzed during runtime.
runtime:
  N: ???