hydra:
  job:
    name: default # change name if needed
    chdir: true
  run:
    dir: runs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - training: default
  - targetnetwork: mlp
  - hypernetwork: mlp
  - optimizer: adam_cosine_onecycle
  - data: target_functions
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

data:
  N: 1000
  n_realizations: 10

targetnetwork:
  num_neurons: [1, 8, 8, 1]
  rngs:
    _target_: flax.nnx.Rngs
    default: 0

hypernetwork:
  num_neurons: [3, 64, 64, 128, null]
  activation_functions:
    _target_: models.get_relu
  rngs:
    _target_: flax.nnx.Rngs
    default: 0
  apply_init_output_layer: ${targetnetwork.replace_weights}

training:
  epochs: 2000
  learning_rate: 1.0e-3
  batch_size: 1024

inference:
  N_examples: 4

seed: 0