import jax
import jax.numpy as jnp
from flax import nnx
from flax.nnx.training.metrics import Metric, Average, MultiMetric
import optax
from typing import Callable, Union, Optional, List, Tuple, Dict
from losses import L2Loss
from typing import Iterator
from tqdm import tqdm
import inspect
import copy
from datetime import datetime
import grain.python as grain
from optax.contrib._reduce_on_plateau import ReduceLROnPlateauState

from data.grain_dataset import build_dataset
from .hypernet_utils import build_state_from_parameters
from .early_stopping import EarlyStopping


#TODO: controllare tutti i tipi e i docstring

def perform_step(
    hypernetwork: nnx.Module,
    targetnetwork: nnx.Module, 
    hypervariables: jax.Array, 
    x: jax.Array, 
    y: jax.Array, 
    criterion: nnx.Module = L2Loss(),
    evaluation: bool = False,
    optimizer: Optional[nnx.Optimizer] = None,
    loss_eval_prev: Optional[float] = None
):
    """
    Perform a single training (or evaluation) step.
    Args:
        hypernetwork (nnx.Module): The hypernetwork that generates the weights for the target network.
        targetnetwork (nnx.Module): The target network whose weights are generated by the hypernetwork.
        hypervariables (jax.Array): The input variables for the hypernetwork.
        x (jax.Array): The input data for the target network.
        y (jax.Array): The ground truth labels for the target network.
        criterion (Callable, optional): The loss function to use. Default is optax.l2_loss.
        evaluation (bool, optional): If True, performs an evaluation step without updating the optimizer. Default is False.
        optimizer (nnx.Optimizer, optional): The optimizer to use for updating the hypernetwork parameters. Required if evaluation is False.
        loss_eval_prev (float, optional): Previous epoch evaluation loss, used for optimizers that require it. Default is None.
    Returns:
        loss (float): The computed loss for the step.
        pred (jax.Array): The predictions made by the target network.
        w (jax.Array): The weights generated by the hypernetwork.
    """
    def forward_pass(hypernetwork, hypervariables, x, y):
        w = hypernetwork(hypervariables)
        graphdef, previous_state = nnx.split(targetnetwork) 
        replace = getattr(targetnetwork, 'replace_weights', True)
        state = nnx.vmap(build_state_from_parameters, in_axes=(None, 0, None), out_axes=0)(previous_state, w, replace=replace) 
        modified_targetnetwork = nnx.merge(graphdef, state)
        pred = nnx.vmap(type(modified_targetnetwork).__call__)(modified_targetnetwork, x)
        if 'weights' in inspect.getfullargspec(criterion.__call__).args:
            loss = jnp.mean(criterion(pred, y, w))
        else:
            loss = jnp.mean(criterion(pred, y))

        return loss, (pred, w)

    if evaluation:
        loss, (pred, w) = forward_pass(hypernetwork, hypervariables, x, y)
    else:
        (loss, (pred, w)), grads = nnx.value_and_grad(forward_pass, has_aux=True)(hypernetwork, hypervariables, x, y)
        optimizer.update(grads, value=loss_eval_prev)

    return loss, pred, w

perform_step = nnx.jit(perform_step, static_argnames=("evaluation"))


def perform_epoch(
        hypernetwork: nnx.Module,
        targetnetwork: nnx.Module,
        train_loader: Iterator,
        val_loader: Iterator,
        optimizer: Optional[nnx.Optimizer] = None,
        criterion: nnx.Module = L2Loss(),
        metrics: MultiMetric = MultiMetric(),
        loss_eval_prev: Optional[float] = None
        ) -> tuple:
    """
    Perform a single training epoch.
    Args:
        hypernetwork (nnx.Module): The hypernetwork that generates the weights for the target network.
        targetnetwork (nnx.Module): The target network whose weights are generated by the hypernetwork.
        train_loader (Iterator): Iterator over training batches (dicts of numpy arrays).
        val_loader (Iterator):   Iterator over validation batches (dicts of numpy arrays).
        optimizer (nnx.Optimizer, optional): The optimizer to use for updating the hypernetwork parameters. Required for training.
        criterion (nnx.Module, optional): The loss function to use. Default is L2Loss().
        metrics (MultiMetric, optional): The metrics to use for evaluation. Default is MultiMetric().
        loss_eval_prev (float, optional): Previous epoch evaluation loss, used for optimizers that require it. Default is None.
    Returns:
        train_loss_epoch (float): The average training loss for the epoch.
        train_metrics (Dict[str, float]): The average training metrics for the epoch.
        val_loss_epoch (float): The average validation loss for the epoch.
        val_metrics (Dict[str, float]): The average validation metrics for the epoch.
    """
    train_loss_epoch = 0.0
    val_loss_epoch = 0.0
    n_samples_train = 0
    n_samples_val = 0
    train_metrics = metrics
    val_metrics = copy.deepcopy(train_metrics)

    for data in train_loader:
        hypervariables = data['hypervars'] # mu, l, k
        x = data['vars'] # x
        y = data['labels'] # y
        train_loss, pred, w = perform_step(hypernetwork = hypernetwork, 
                                           targetnetwork = targetnetwork,
                                           hypervariables = hypervariables, 
                                           x = x, 
                                           y = y, 
                                           optimizer = optimizer, 
                                           criterion = criterion, 
                                           loss_eval_prev = loss_eval_prev)
        train_loss_epoch += train_loss * x.shape[0]
        n_samples_train += x.shape[0]
        train_metrics.update(predictions=pred, targets=y)
    train_loss_epoch /= n_samples_train

    for data in val_loader:
        hypervariables = data['hypervars'] # mu, l, k
        x = data['vars'] # x
        y = data['labels'] # y
        val_loss, pred, w = perform_step(hypernetwork = hypernetwork, 
                                         targetnetwork = targetnetwork,
                                         hypervariables = hypervariables, 
                                         x = x, 
                                         y = y, 
                                         criterion = criterion,
                                         evaluation = True)
        val_loss_epoch += val_loss * x.shape[0]
        n_samples_val += x.shape[0]
        val_metrics.update(predictions=pred, targets=y)
    val_loss_epoch /= n_samples_val

    return train_loss_epoch, train_metrics.compute(), val_loss_epoch, val_metrics.compute()

#perform_epoch = nnx.jit(perform_epoch, static_argnames=("train_loader", "val_loader"))

def train_model(
        hypernetwork: nnx.Module,
        targetnetwork: nnx.Module,
        train_source: grain.RandomAccessDataSource,
        val_source: grain.RandomAccessDataSource,
        optimizer: nnx.Optimizer,
        num_epochs: int,
        batch_size: int = 32,
        in_memory: bool = True,
        criterion: nnx.Module = L2Loss(),
        metrics: Optional[Union[MultiMetric, Dict[str, Metric]]] = None,
        early_stopping: Optional[EarlyStopping] = None,
        early_stopping_metric: Optional[Union[str, int]] = None,
        plateau_scheduler_metric: Optional[Union[str, int]] = None,
        log_file_path: Optional[str] = None,
        ) -> tuple:
    """
    Train the hypernetwork for a specified number of epochs, with optional early stopping and logging.
    Args:
        hypernetwork (nnx.Module): The hypernetwork that generates the weights for the target network.
        targetnetwork (nnx.Module): The target network whose weights are generated by the hypernetwork.
        train_source (grain.RandomAccessDataSource): The training data source.
        val_source   (grain.RandomAccessDataSource): The validation data source.
        optimizer (nnx.Optimizer): The optimizer to use for updating the hypernetwork parameters.
        num_epochs (int): The number of epochs to train the model.
        batch_size   (int): Batch size for both train and val pipelines.
        # TODO: check if necessary to do here in_memory
        in_memory    (bool): Whether the source is fully in RAM (controls threading/prefetch).
        criterion (Callable, optional): The loss function to use. Default is optax.l2_loss.
        metrics (Dict[str, Callable], optional): A dictionary of metric functions to compute during the training. Default is None.
        early_stopping (EarlyStopping, optional): An EarlyStopping object to monitor validation performance and stop training early if needed. Default is None.
        early_stopping_metric (str or int, optional): The metric to monitor for early stopping. Can be a metric name or index. Default is None (uses the validation loss).
        plateau_scheduler_metric (str or int, optional): The metric to monitor for learning rate plateau scheduling. Can be a metric name or index. Default is None (uses the validation loss).
        log_file_path (str, optional): Path to a log file where training progress will be logged. Default is None (no logging).
    Returns:
        history (Dict[str, List[float]]): A dictionary containing training and validation losses and metrics for each epoch.
    """

    if not isinstance(metrics, MultiMetric):
        if isinstance(metrics, dict):
            metrics = MultiMetric(**metrics)
        elif metrics is None:
            metrics = MultiMetric()
        else:
            raise ValueError("metrics must be either a MultiMetric instance, a dictionary of metrics, or None.")

    history = {'train_results': [], 'val_results': [],  'lrs': []}

    early_stopping_metric_name = check_metric_name(early_stopping_metric, metrics._metric_names)
    if early_stopping_metric_name == -1:
        raise ValueError("Invalid early_stopping_metric. It must be either None, a valid metric name or a valid metric index.")
    plateau_scheduler_metric_name = check_metric_name(plateau_scheduler_metric, metrics._metric_names)
    if plateau_scheduler_metric_name == -1:
        raise ValueError("Invalid plateau_scheduler_metric. It must be either None, a valid metric name or a valid metric index.")

    if log_file_path:
        with open(log_file_path, "w") as f:
            f.write(f"Training Log - Start time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    loss_plateau_scheduler = jnp.inf

    pbar = tqdm(range(num_epochs))
    for epoch in pbar:
        metrics.reset()
        train_iter = build_dataset(train_source, is_training=True,  batch_size=batch_size, in_memory=in_memory, seed=epoch)
        val_iter   = build_dataset(val_source,   is_training=False, batch_size=batch_size, in_memory=in_memory)
        train_loss, train_metrics, val_loss, val_metrics = perform_epoch(hypernetwork=hypernetwork,
                                                                       targetnetwork=targetnetwork,
                                                                       train_loader=train_iter, 
                                                                       val_loader=val_iter, 
                                                                       optimizer=optimizer, 
                                                                       criterion=criterion, 
                                                                       metrics=metrics,
                                                                       loss_eval_prev=loss_plateau_scheduler)
        train_results_epoch = {'loss': train_loss, **train_metrics}
        val_results_epoch   = {'loss': val_loss, **val_metrics}
        # if reduce on plateau present, save it, otherwise constant 1.0 (NON MOLTO GENERALE: PREVEDE CHE PLATEAU SIA SECONDO OPTAX IN CHAIN)
        if isinstance(optimizer.opt_state[1], ReduceLROnPlateauState):
            lr_scale = optimizer.opt_state[1].scale.value
        else:
            lr_scale = 1.0
        history['train_results'].append(train_results_epoch)
        history['val_results'].append(val_results_epoch)
        history['lrs'].append(lr_scale)
    
        log_compact = (
            f"Epoch {epoch+1}/{num_epochs} - "
            f"Train: {compact_format(train_results_epoch)} - "
            f"Val: {compact_format(val_results_epoch)} - "
            f"LR Multiplier: {lr_scale:.4f}"
        )
        log_detail = f"Epoch {epoch+1}/{num_epochs} - " + \
              f"Train: {', '.join(f'{k}: {v.item():.8f}' for k,v in train_results_epoch.items())} - " + \
              f"Val: {', '.join(f'{k}: {v.item():.8f}' for k,v in val_results_epoch.items())} - " + \
              f"LR multiplier: {lr_scale:.8f}"
        pbar.set_description(log_compact)

        if log_file_path:
            with open(log_file_path, "a") as f:
                f.write(log_detail + "\n")

        loss_plateau_scheduler = val_results_epoch[plateau_scheduler_metric_name]
        if early_stopping:
            loss_early_stopping = val_results_epoch[early_stopping_metric_name]
            early_stopping(current_loss=loss_early_stopping,
                           current_model=hypernetwork,
                           current_epoch=epoch)
            if early_stopping.should_stop:
                print(f"Early stopping at epoch {epoch+1}. Best epoch was {early_stopping.best_epoch+1} with loss {early_stopping.best_loss:.8f}.")
                if log_file_path:
                    with open(log_file_path, "a") as f:
                        f.write(f"Early stopping at epoch {epoch+1}. Best epoch was {early_stopping.best_epoch+1} with loss {early_stopping.best_loss:.8f}.\n")
                # if early_stopping.best_model:
                #     hypernetwork = early_stopping.best_model
                if early_stopping.best_state:
                    nnx.update(hypernetwork, early_stopping.best_state)
                break

    if log_file_path:
        with open(log_file_path, "a") as f:
            f.write(f"Training Log - End time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

    return history

@nnx.jit
def compute(loss: nnx.Module, preds: jax.Array, targets: jax.Array, weights: jax.Array) -> jax.Array:
    """
    Auxiliary function to compute a loss, handling both cases where the loss requires weights and where it does not.
    Args:
        loss (nnx.Module): The loss to compute. It must take as inputs the predictions and targets.
        preds (jax.Array): The predicted values.
        targets (jax.Array): The ground truth values.
        weights (jax.Array): The weights generated by the hypernetwork.
    Returns:
        jax.Array: The computed loss value.
    """
    if 'weights' in inspect.getfullargspec(loss.__call__).args:
        return loss(preds, targets, weights)
    else:
        return loss(preds, targets)

def check_metric_name(metric: Union[str, int, None], name_metrics: Tuple[str]) -> int:
    """
    Auxiliary function to check if the given metric name or index is valid.
    Args:
        metric (str, int, or None): The metric to check. Can be a metric name, index, or None.
        name_metrics (Tuple[str]): A tuple of valid metric names.
    Returns:
        str: The valid metric name if found, or -1 if invalid.
    """
    if metric is None:
        return 'loss'
    if isinstance(metric, str):
        if metric not in name_metrics:
            return -1
        return metric
    elif isinstance(metric, int):
        if metric < 0 or metric >= len(name_metrics):
            return -1
        return name_metrics[metric]
    else:
        return -1
    
def compact_format(metrics_dict, k=2):
        items = list(metrics_dict.items())[:k] 
        return ', '.join(f'{key}: {val.item():.4f}' for key, val in items)
