loss_plots:
  loss_linear:
    _target_: postprocessing.plot_loss_curves

  loss_semilogx:
    _target_: postprocessing.plot_loss_curves
    logx: True

  loss_loglog:
    _target_: postprocessing.plot_loss_curves
    logx: True
    logy: True


output_plots:
  default_predictions:
    _target_: postprocessing.generate_toy_plots
    hypervars_set:
      - [0.5, 0.5, 0.5]
      - [1.0, 0.5, 1.0]
      - [-1.0, 0.5, -1.0]
    var_domains: ${data_source.base_toy.var_domains}
    exact_function: ${data_source.base_toy.f}
    n_points: 400