# @package _global_

problem_name: turbulence

defaults:
  - /preprocessing: turbulence
  - /data_source: turbulence
  - /training: turbulence
  - /model: turbulence_siren
  - /postprocessing: turbulence