_target_: models.MLP

num_neurons: [1, 64, 64, 128, null]
activation_functions:
  _target_: models.get_tanh
rngs:
  _target_: flax.nnx.Rngs
  default: ${seed}
apply_init_output_layer: ${targetnetwork.replace_weights}